version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Copying files to S3
      - aws s3 cp ./index.html s3://paveltestdomain.com/index.html --acl public-read
  post_build:
    commands:
      - echo built completed on `date`
artifacts:
  files:
    - index.html